acereadymade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acereadymade_app.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('dashboard/', include('dashboard.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acereadymade_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from acereadymade_app import views


app_name = 'acereadymade_app'

urlpatterns = [
    # Account Parts
    path('', IndexView.as_view(), name='index'),
    path('signup/', CustomerSignUpView.as_view(), name='signup'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate,
            name='activate'),

    path('details/', DetailsView.as_view(), name='details'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('base/', BaseView.as_view(), name='base'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('myaccount/', MyAccoutView.as_view(), name='myaccount'),
    path('wishlist/', WishListView.as_view(), name='wishlist'),

    path('products/<int:category_id>/<slug:category_slug>/', ProductList.as_view(), name='product_list_by_category'),
    # category's product list

    path('products/', ProductList.as_view(), name='product_list'),
    path('products/detail/<slug:product_slug>/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    # product detail

]

cart/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from . import views
from acereadymade_app import views


app_name = 'cart'

urlpatterns = [
    # Account Parts
    path('detail/', DetailView.as_view(), name='detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('ProceedCheckout/', ProceedCheckoutView.as_view(), name='proceedcheckout'),
    path('ViewCart/', ViewCartView.as_view(), name='viewcart'),
    path('OrderSummery/', OrderView.as_view(), name='order_list'),

    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', full_remove, name='full_remove'),
# addtocart_2
]

cart/models.py
from django.db import models
from acereadymade_app.models import Product, User


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

    class Meta:
        db_table = 'Cart'  # defining the name of the table
        ordering = ['date_added']

    def __str__(self):
        return str(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # i.e if the product is deleted then any mention of that product is also deleted
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, blank=False)
    quantity = models.IntegerField()
    price = models.DecimalField(blank=False, decimal_places=2, null=True, max_digits=15)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):  # to calculate the total price
        return self.product.price * self.quantity

    def __str__(self):
        return str(self.product)


class Order(models.Model):
    Countries = (
        (1, 'Nepal'),
        (1, 'India'),
        (1, 'Bangladesh'),
    )
    State = (
        (1, 'Kathmandu'),
        (1, 'Lalitpur'),
        (1, 'Bhaktapur'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=250, blank=False)
    l_name = models.CharField(max_length=250, blank=False)
    company_name = models.CharField(max_length=250, blank=True, null=True)
    country = models.PositiveSmallIntegerField(choices=Countries)
    street_add = models.CharField(max_length=250, blank=False)
    apartment = models.CharField(max_length=250, blank=True, null=True)
    town = models.CharField(max_length=250, blank=False)
    state = models.PositiveSmallIntegerField(choices=State)
    postcode = models.CharField(max_length=250, blank=True, null=True)
    phone = models.IntegerField(blank=False)
    email = models.EmailField(max_length=250, blank=False)
    information = models.CharField(max_length=500, blank=True, null=True)

cart/forms.py
from django import forms
from .models import *
from . models import Order

Countries = (
    ('1', 'Nepal'),
    ('2', 'India'),
    ('3', 'Bangladesh'),
)

State = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
)


class OrderForm(forms.Form):
    f_name = forms.CharField(max_length=30, required=True)
    l_name = forms.CharField(max_length=30, required=True)
    company_name = forms.CharField(max_length=30, required=True)
    country = forms.ChoiceField(choices=Countries)
    street_add = forms.CharField(max_length=30, required=True)
    apartment = forms.CharField(max_length=30, required=False)
    town = forms.CharField(max_length=250, required=True)
    state = forms.ChoiceField(choices=State)
    postcode = forms.CharField(max_length=250, required=False)
    phone = forms.IntegerField(required=True)
    email = forms.EmailField(max_length=250, required=True)
    information = forms.CharField(max_length=500, required=False)

    class Meta:
        model = Order
        fields = ('f_name', 'l_name', 'email', 'Company_name', 'Country', 'street_add', 'apartment', 'town', 'state',
                  'postcode', 'phone', 'email', 'information',)

cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, FormView, ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from acereadymade_app.models import *
from .models import Cart, CartItem, Order
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMessage
from .forms import OrderForm








class DetailView(ListView):
    template_name = 'cart/detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['featured_products'] = Product.objects.filter(available=True, featured=True).order_by('-created')[0:5]

        return context


class CartView(ListView):
    template_name = 'cart/cart.html'


class ProceedCheckoutView(TemplateView):
    form_class = OrderForm
    template_name = 'cart/proceed_checkout.html'
    model = Cart

    def get_context_data(self, **kwargs):
        context = super(ProceedCheckoutView, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user = self.request.user
            cart = Cart.objects.get(user=self.request.user)
            context['carts'] = CartItem.objects.filter(cart=cart)

        context['categories'] = Category.objects.all()
        context['form'] = self.form_class()
        total = 0
        counter = 0
        for cart_item in CartItem.objects.all():
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
        context['total'] = total
        return context

    def post(self, request):
        form = self.form_class(request.POST)
        print(55555555555,request.POST)
        cart = Cart.objects.get(user=self.request.user)
        cart_item = CartItem.objects.filter(cart=cart)
        if form.is_valid():
            form_data = request.POST
            for item in cart_item:
                print(13333333333333333333333333333333333333)
                order = Order.objects.create(
                    user=self.request.user,
                    product=item.product,
                    f_name=form_data['f_name'],
                    l_name=form_data['l_name'],
                    country=form_data['country'],
                    street_add=form_data['street_add'],
                    apartment=form_data['apartment'],
                    town=form_data['town'],
                    state=form_data['state'],
                    postcode=form_data['postcode'],
                    phone=form_data['phone'],
                    email=form_data['email'],
                    information=form_data['information'],
                )
                if form_data['company_name']:
                    order.company_name = form_data['company_name']

                if form_data['apartment']:
                    order.apartment = form_data['apartment']

                if form_data['postcode']:
                    order.apartment = form_data['postcode']

                if form_data['information']:
                    order.apartment = form_data['information']

                order.save()
                item.delete()
            return redirect('cart:order_list')

        return render(request, 'cart/proceed_checkout.html')


class ViewCartView(TemplateView):
    template_name = 'cart/viewfinish.html'


class OrderView(TemplateView):
    template_name = 'cart/ordersummery.html'

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        print(222222222222222222222222222222222222222222222222)
        context['categories'] = Category.objects.all()
        context['orders'] = Order.objects.filter(user=self.request.user)
        return context






# def _cart_id(request):  # checking if a session id has been created on the customer browser
#     cart = request.session.session_key
#     if not cart:
#         cart = request.session.create()
#     return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    print(11111111111111111111111111111111111111111, request.user)
    if request.user.is_authenticated:
        user = request.user
    else:
        return redirect('acereadymade_app:login')

    try:  # getting a cart by id and if it does'nt exist then we will create the cart
        cart = Cart.objects.get(user=user)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            user=request.user,
            cart_id=request.user.id
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)  # adding product to cart
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):  # this method is used to display cart
    try:
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        # products = Product.objects.get(price=price(request))

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY  # processing payments using stripe api
    stripe_total = int(total * 100)
    description = 'Perfect Cushion Store - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':  # doing this to get the stripe token and email address in order to create the customer record and the charge
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billingName = request.POST['stripeBillingName']  # to get Billing Name from stripe payment form
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingCity = request.POST['stripeBillingAddressCity']
            billingState = request.POST['stripeBillingAddressState']
            billingPostcode = request.POST['stripeBillingAddressZip']
            billingCountry = request.POST['stripeBillingAddressCountryCode']
            shippingName = request.POST['stripeShippingName']
            shippingAddress1 = request.POST['stripeShippingAddressLine1']
            shippingCity = request.POST['stripeShippingAddressCity']
            shippingState = request.POST['stripeShippingAddressState']
            shippingPostcode = request.POST['stripeShippingAddressZip']
            shippingCountry = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            charge = stripe.Charge.create(
                amount=stripe_total,
                currency='gbp',
                description=description,
                customer=customer.id
            )
            ''' Creating the Order '''
            try:
                order_details = Order.objects.create(
                    token=token,
                    total=total,
                    emailAddress=email,
                    billingName=billingName,
                    billingAddress1=billingAddress1,
                    billingCity=billingCity,
                    billingState=billingState,
                    billingPostcode=billingPostcode,
                    billingCountry=billingCountry,
                    shippingName=shippingName,
                    shippingAddress1=shippingAddress1,
                    shippingCity=shippingCity,
                    shippingState=shippingState,
                    shippingPostcode=shippingPostcode,
                    shippingCountry=shippingCountry
                )
                order_details.save()
                for order_item in cart_items:  # every time the for loop runs a cart item is assigned to the order item variable
                    oi = OrderItem.objects.create(
                        product=order_item.product.name,
                        quantity=order_item.quantity,
                        price=order_item.product.price,
                        order=order_details
                    )  # oi variable is getting the value of each order item in order to create the order item record
                    oi.save()
                    '''Reduce stock when order is placed or saved'''
                    products = Product.objects.get(id=order_item.product.id)
                    products.stock = int(order_item.product.stock - order_item.quantity)
                    products.save()
                    order_item.delete()
                    '''The terminal will print this message when the order is saved'''
                    print('The order has been created')
                try:
                    ''' Calling the sendEmail function '''
                    sendEmail(order_details.id)
                    print('The order email has been sent to the customer.')
                except IOError as e:
                    return e
                return redirect('order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e

    return render(request, 'cart/viewfinish.html', dict(cart_items=cart_items, total=total, counter=counter, data_key=data_key,
                                             stripe_total=stripe_total, description=description))


def cart_remove(request, product_id):  # to remove a quantity product from cart
    cart = Cart.objects.get(user=request.user)

cart/templates/cart/cart.html
{% extends 'acereadymade/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">

    <title>Cart-Ace Radymade</title>


    {% block content %}

            <div class="contacthome">
            <div class="home_icon">
              <div class="container">
                <div class="row">
                  <div class="col-md-2">
                    <h1><a href="index.php"></a><g>Cart</g></h1>
                  </div>
                </div>
              </div>
            </div>
          </div>



         <div class="empaty">
         	<div class="container">
         			<div class="col-md-12">
         				<h1>Your cart is currently empty.</h1>
         				<h2><a href="shop.php">Return to shop</a></h2>
         			</div>
         		</div>
         	</div>

{% endblock %}

cart/templates/cart/ordersummery.html
{% extends 'acereadymade/base.html' %}

{% block content %}
<div class="ordersummary">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Order Summary</h1>
            </div>
        </div>
    </div>
</div>


<div class="Product_name">
    <div class="container">
      {% for orders in orders %}
        <div class="Product_name1">
            <div class="row">
                <div class="col-md-2">
                </div>

                <div class="col-md-3">
                    <h1>Product Name</h1>
                </div>
                <div class="col-md-3">
                    <h1>Unit Price</h1>
                </div>
                <div class="col-md-3">
                    <h1>Total Amount</h1>
                </div>

                <div class="col-md-1">
                </div>

                <div class="col-md-1">
                </div>
                <div class="col-md-10">
<!--                    <h2>No products were added to the wishlist</h2>-->
                </div>

                <div class="col-md-2">
                </div>

                <div class="col-md-3">
                    <h1>{{ orders.product.name }}</h1>
                </div>
                <div class="col-md-3">
                    <h1>Unit Price</h1>
                </div>
                <div class="col-md-3">
                    <h1>{{ orders.product.price }}</h1>
                </div>

                <div class="col-md-1">
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

cart/templates/cart/viewfinish.html
{% extends 'acereadymade/base.html' %}
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/style.css">


    <link href="vendors/line-icon/css/simple-line-icons.css" rel="stylesheet">
    <link href="vendors/elegant-icon/style.css" rel="stylesheet">

    <link href="vendors/bootstrap-selector/css/bootstrap-select.min.css" rel="stylesheet">


    <link href="css/style.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="vendors/owl-carousel/owl.carousel.min.css" rel="stylesheet">


    <title>Cart-Ace Radymade</title>

    {% block content %}
    <div class="contacthome">
        <div class="home_icon">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h1><a href="index.php"></a>
                            <g><a href="shop.php">Shop</a></g>
                            /Cart
                        </h1>
                        <g></g>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="viewcart_shopping">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <h1>Shopping Cart</h1>
                </div>

                <div class="col-md-8">
                </div>

                <div class="col-md-2">
                    <h2><a href="{% url 'cart:proceedcheckout' %}"> Proced to checkout</a></h2>
                </div>
            </div>
        </div>
    </div>


    <div class="cart_ProductName">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <div class="col-md-8">
                    <div class="cart_ProductName-1">

                        <div class="row">
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-4">
                                <h1>Product Name</h1>
                            </div>


                            <div class="col-md-2">
                                <h1>Unit Price</h1>
                            </div>


                            <div class="col-md-1">
                                <h1>Qty</h1>
                            </div>


                            <div class="col-md-1">
                                <h1>Subtotal</h1>
                            </div>

                            {% for cart_item in cart_items %}

                            <div class="col-md-1">
                            </div>


                            <div class="col-md-1">
                            </div>


                            <div class="col-md-2">
                                <img src="{{ cart_item.product.image.url }}">
                            </div>

                            <div class="col-md-4">
                                <h3><a href="shop_cart.php">{{ cart_item.product.name }}<br> SAREE WITH BLOUSE</a></h3>

                                Qty: {{ cart_item.quantity }} x Rs{{ cart_item.product.price }}
                            </div>

                            <div class="col-md-1">
                                <h4>₨{{ cart_item.product.price }}</h4>
                            </div>


                            <div class="col-md-2">
                                <form>
                                    {% if cart_item.quantity < cart_item.product.stock %}
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}">
                                    <div class="value-button" id="decrease" onclick="decreaseValue()"
                                         value="Decrease Value">-
                                    </div>
                                    </a>
                                    <input type="number" id="number" value="{{ cart_item.quantity }}"/>
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}">
                                    <div class="value-button" id="increase" onclick="increaseValue()"
                                         value="Increase Value">+
                                    </div>
                                    </a>
                                    {% else %}
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}">
                                    <div class="value-button" id="decrease1" onclick="decreaseValue()"
                                         value="Decrease Value">-
                                    </div>
                                    </a>
                                    {% endif %}
                                </form>
                            </div>

                            <div class="col-md-1">
                                <h4><b>₨{{ cart_item.sub_total }}</b></h4>
                            </div>

                            {% endfor %}

                            <div class="col-md-12">
                                <div class="dropcart">

                                    <h1>
                                        <class
                                        ="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="COURSES" id="navbarDropdown"
                                           role="button" data-toggle="dropdown" aria-haspopup="true"
                                           aria-expanded="false">
                                            DISCOUNT CODE</a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <class
                                            ="dropdown-item"><h2>Enter your coupon code if you have one:</h2>
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <input type="text" name="text">
                                                </div>

                                                <div class="col-md-3">
                                                    <a href="Aply-Cupon.php"><h3>Aply Cupon</h3></a>
                                                </div>
                                                </class="dropdown-item">
                                            </div>
                                            </class="nav-item>
                                    </h1>
                                    </class="dropdown-item">
                                </div>
                                </class="nav-item>
                                </h1>


                                <div class="contineu">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <h1><a href="{% url 'acereadymade_app:index' %}">Contineu Shopping</a></h1>
                                            </div>


                                            <div class="col-md-6">
                                            </div>


                                            <div class="col-md-3">
                                                <h1><a href="#">Update Cart</a></h1>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                    <div class="col-md-4">
                        <div class="dropcart">
                            <div class="dropcart_1">
                                <h1>
                                    <class
                                    ="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="COURSES" id="navbarDropdown1"
                                       role="button"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        CART TOTALS</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <div class="row">

                                                                                        <div class="col-md-6">

                                                                                            <h2>Subtotal</h2>
                                                                                        </div>

                                                                                        <div class="col-md-1">
                                                                                            <h2>₨{{ cart_item.sub_total }}</h2>
                                                                                        </div>


                                            <div class="col-md-6">

                                                <h2>Grand Total </h2>
                                            </div>

                                            <div class="col-md-1">
                                                <h2><b>₨{{ total }}</b></h2>
                                            </div>

                                            <h2><a href="{% url 'cart:proceedcheckout' %}"> Proced to checkout</a></h2>
                                        </div>
                                    </div>
                                    </class="nav-item>
                                </h1>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {% endblock %}

    <!-- Product futtr_0 end-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script type="text/javascript">
    	function increaseValue() {
  var value = parseInt(document.getElementById('number').value, 10);
  value = isNaN(value) ? 0 : value;
  value++;
  document.getElementById('number').value = value;
}

function decreaseValue() {
  var value = parseInt(document.getElementById('number').value, 10);
  value = isNaN(value) ? 0 : value;
  value < 1 ? value = 1 : '';
  value--;
  document.getElementById('number').value = value;
}

    </script>
    {% endblock %}
    </body>
</html>