acereadymade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acereadymade_app.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('dashboard/', include('dashboard.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acereadymade_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from acereadymade_app import views


app_name = 'acereadymade_app'

urlpatterns = [
    # Account Parts
    path('', IndexView.as_view(), name='index'),
    path('signup/', CustomerSignUpView.as_view(), name='signup'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate,
            name='activate'),

    path('details/', DetailsView.as_view(), name='details'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('base/', BaseView.as_view(), name='base'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('myaccount/', MyAccoutView.as_view(), name='myaccount'),
    path('wishlist/', WishListView.as_view(), name='wishlist'),

    path('products/<int:category_id>/<slug:category_slug>/', ProductList.as_view(), name='product_list_by_category'),
    # category's product list

    path('products/', ProductList.as_view(), name='product_list'),
    path('products/detail/<slug:product_slug>/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    # product detail

]

cart/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from . import views
from acereadymade_app import views


app_name = 'cart'

urlpatterns = [
    # Account Parts
    path('detail/', DetailView.as_view(), name='detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('ProceedCheckout/', ProceedCheckoutView.as_view(), name='proceedcheckout'),
    path('ViewCart/', ViewCartView.as_view(), name='viewcart'),
    path('OrderSummery/', OrderView.as_view(), name='order_list'),

    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', full_remove, name='full_remove'),
# addtocart_2
]

search/urls.py
from django.urls import path, re_path
from search import views


app_name = 'search'


urlpatterns = [

    re_path(r'^.*/', views.searchResult, name='searchResult'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from acereadymade_app.models import Product
from django.db.models import Q
# Create your views here.
def searchResult(request):
    products = None
    query = None
    print(11111111111111111111111111111111111111111111111111111, request.GET.get('q'))
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

search/templates/search.html
{% extends 'acereadymade/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <link href="{% static 'vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/elegant-icon/style.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">


    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100i,200,400&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<section class="our_latest_product">
    <div class="container">
        <div class="s_m_title">
        </div>
        <div>
            <p class="text-center my_title"> You have searched for: <b>"{{ query }}"</b></p>
        </div>
<!--        <div class="l_product_slider owl-carousel">-->
<!--            <div class="item">-->
        {% for product in products %}

            <div class="col-md-6 col-lg-3 ftco-animate">
                <div class="l_product_item">
                    <div class="l_p_img">
                        <a href="{% url 'acereadymade_app:product_detail' product.slug product.id %}">
                        <img src="{{product.image.url}} " alt="">
                        </a>

                        <h1>-30</h1>
                    </div>
                    <div class="l_p_text">
                        <ul>
                            <li class="p_icon"><a href="#"><i class="icon_piechart"></i></a></li>
                            <li><a class="add_cart_btn" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a></li>
                            <li class="p_icon"><a href="#"><i class="icon_heart_alt"></i></a></li>
                        </ul>
                        <h4>{{ product.name }}<br>With Attached Blowse</h4>
                        <h5>
                            <del>₨ 3,400.00</del>
                            ₨ {{ product.price }}
                        </h5>
                    </div>
                </div>
            </div>
                {% endfor %}

<!--            </div>-->
<!--        </div>-->
    </div>
</section>
{% endblock %}
{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
{% endblock %}