acereadymade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acereadymade_app.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('dashboard/', include('dashboard.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from . import views
from acereadymade_app import views


app_name = 'cart'

urlpatterns = [
    # Account Parts
    path('detail/', DetailView.as_view(), name='detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('ProceedCheckout/', ProceedCheckoutView.as_view(), name='proceedcheckout'),
    path('ViewCart/', ViewCartView.as_view(), name='viewcart'),
    path('OrderSummery/', OrderView.as_view(), name='order_list'),

    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', full_remove, name='full_remove'),
# addtocart_2
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard.as_view(), name='dashboard'),
    path('base/', base.as_view(), name='base'),
    path('categories/', categories.as_view(), name='categories'),
    path('add_category/', add_categories.as_view(), name='cat_add_modal'),
    path('order/', order.as_view(), name='order'),
    path('users/', users.as_view(), name='users'),
    path('products/', products.as_view(), name='products'),
    path('add_products/', add_products.as_view(), name='products_add'),
    path('product/delete/<int:product_id>/', DeleteProduct.as_view(), name='delete_product'),
    path('category/delete/<int:category_id>/', DeleteCategory.as_view(), name='delete_category'),
    path('user/delete/<int:user_id>/', DeleteUser.as_view(), name='delete_user'),
    path('edit_category/<int:category_id>/', EditCategory.as_view(), name='edit_category'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('edit_category/<int:category_id>/', EditCategory.as_view(), name='edit_category'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.utils import timezone
from .models import *
from acereadymade_app.models import *
from django.core.files.images import ImageFile


class AdminLogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)

    class Meta:
        models = User
        fields = ('username', 'passwords', )


class AddCategoryForm(forms.Form):
    name = forms.CharField(max_length=150)
    slug = forms.CharField(max_length=150)

    class Meta:
        fields = ('name', 'slug')


class AddProductForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    name = forms.CharField(max_length=150)
    slug = forms.SlugField(max_length=150)
    image = forms.ImageField()
    description = forms.CharField(max_length=500)
    price = forms.DecimalField(max_digits=10, decimal_places=2)
    stock = forms.IntegerField()
    available = forms.BooleanField(required=False)
    featured = forms.BooleanField(required=False)
    latest = forms.BooleanField(required=False)
    topkurtha = forms.BooleanField(required=False)
    topfeatured = forms.BooleanField(required=False)

class EditCategoryForm(forms.Form):
    name = forms.CharField(max_length=150)
    slug = forms.CharField(max_length=150)

    class Meta:
        fields = ('name', 'slug')

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, View, FormView, ListView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from acereadymade_app.models import *
from cart.models import *
from .forms import AddCategoryForm, AddProductForm, EditCategoryForm, AdminLogInForm
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User

from PIL import Image
import os


# Create your views here.
class Login(View):
    success_url = reverse_lazy('dashboard:dashboard')
    template_name = 'dashboard/login-simple.html'
    form_class = AdminLogInForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'login_error': 'Please Login to Continue', 'form': form})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(555555555555555555,request.POST)
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(request, user)
            return redirect(self.success_url)
        else:
            form = self.form_class()
            return render(request, 'dashboard/login-simple.html', {'form': form})


class LogoutView(View):
    success_url = reverse_lazy('dashboard:login')


    def get(self, request):
        logout(request)
        return redirect(self.success_url)


class dashboard(TemplateView):
    template_name = 'dashboard/index.html'




class base(TemplateView):
    template_name = 'dashboard/base.html'

class categories(TemplateView):
    template_name = 'dashboard/m_categories.html'

    def get_context_data(self, **kwargs):
        context = super(categories, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class add_categories(TemplateView):
    success_url = reverse_lazy('dashboard:categories')
    form_class = AddCategoryForm
    template_name = 'dashboard/modals.html'

    def get_context_data(self, **kwargs):
        context = super(add_categories, self).get_context_data()
        context['add_categories'] = Category.objects.all()
        context['form'] = self.form_class()
        return context

    def post(self, request):
        form = self.form_class(request.POST)
        print(11111111111111111, request.POST)
        if form.is_valid():
            Category.objects.create(name=request.POST['name'], slug=request.POST['slug']).save()

        else:
            return render(request, 'dashboard/m_categories.html')

        return redirect(self.success_url)


class order(TemplateView):
    template_name = 'dashboard/m_orders.html'

    def get_context_data(self, **kwargs):
        context = super(order, self).get_context_data(**kwargs)
        # print(222222222222222222222222222222222222222222222222)
        # context['categories'] = Category.objects.all()
        context['orders'] = Order.objects.all()
        return context


class users(TemplateView):
    template_name = 'dashboard/m_users.html'

    def get_context_data(self, **kwargs):
        context = super(users, self).get_context_data()
        context['users'] = User.objects.all()
        return context

class products(TemplateView):
    template_name = 'dashboard/m_products.html'

    def get_context_data(self, **kwargs):
        context = super(products, self).get_context_data()
        context['products'] = Product.objects.all()
        return context


class add_products(TemplateView):
    success_url = reverse_lazy('dashboard:products')
    form_class = AddProductForm
    template_name = 'dashboard/add_products.html'

    def get_context_data(self, **kwargs):
        context = super(add_products, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['form'] = self.form_class()
        return context

    def post(self, request):
        category = Category.objects.get(id=request.POST['category'])
        print(request.POST)
        product = Product.objects.create(category=category, name=request.POST['name'], slug=request.POST['slug'],
                               description=request.POST['description'], price=request.POST['price'],
                               image=request.FILES['image'], stock=request.POST['stock'])
        try:
            featured = request.POST['featured']
            product.featured = True
        except KeyError:
            product.featured = False

        try:
            available = request.POST['available']
            product.available = True
        except KeyError:
            product.available = False

        try:
            topkurtha = request.POST['topkurtha']
            product.topkurtha = True
        except KeyError:
            product.topkurtha = False

        try:
            latest = request.POST['latest']
            product.latest = True
        except KeyError:
            product.latest = False

        try:
            topfeatured = request.POST['topfeatured']
            product.topfeatured = True
        except KeyError:
            product.topfeatured = False

        product.save()
        return redirect(self.success_url)

        # size_300 = (255, 399)
        # size_700 = (600, 938)
        #
        # for f in os.listdir('.'):
        #     if f.endswith('.jpg'):
        #         i = Image.open(f)
        #         fn, fext = os.path.splitext(f)
        #
        #         i.thumbnail(size_300)
        #         i.save('small/{}_small{}'.format(fn, fext))
        #
        #         i.thumbnail(size_700)
        #         i.save('large/{}_large{}'.format(fn, fext))




    # def post(self, request):
    #     form = self.form_class(request.POST)
    #     print(11111111111111111, request.POST)
    #     if form.is_valid():
    #         Category.objects.create(name=request.POST['name'], slug=request.POST['slug']).save()
    #
    #     else:
    #         return render(request, 'dashboard/m_categories.html')
    #
    #     return redirect(self.success_url)

class DeleteProduct(View):

    def post(self, request, **kwargs):
        product_id = kwargs['product_id']
        Product.objects.get(id=product_id).delete()
        return redirect('dashboard:products')


class DeleteCategory(View):

    def post(self, request, **kwargs):
        category_id = kwargs['category_id']
        Category.objects.get(id=category_id).delete()
        return redirect('dashboard:categories')

class DeleteUser(View):

    def post(self, request, **kwargs):
        user_id = kwargs['user_id']
        User.objects.get(id=user_id).delete()
        return redirect('dashboard:users')


class EditCategory(View):
    success_url = reverse_lazy('dashboard:categories')

    def get(self, request, **kwargs):
        form = EditCategoryForm
        category = Category.objects.get(id=kwargs['category_id'])
        return render(request, 'dashboard/editmodals.html', {'category': category, 'form': form})

    def post(self, request, **kwargs):
        form_data = request.POST
        print(22222222222222222222,form_data)
        category = Category.objects.get(id=kwargs['category_id'])
        category.name = form_data['name']
        category.slug = form_data['slug']
        category.save()
        return redirect('dashboard:categories')

dashboard/templates/dashboard/m_categories.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% block table %}
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-xs-12 mb-1">
                <h2 class="content-header-title"></h2>
            </div>
            <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
                <div class="breadcrumb-wrapper col-xs-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Tables</a>
                        </li>
                        <li class="breadcrumb-item active">Basic Tables
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="content-body"><!-- Basic Tables start -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Add Categories</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a href="{% url 'dashboard:cat_add_modal' %}" data-action="#"><i
                                            class="icon-plus4"></i></a></li>
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                    <li><a data-action="close"><i class="icon-cross2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body collapse in">
                            <div class="card-block card-dashboard">
                                <p class="card-text"></p>
                                <p><span class="text-bold-600">Category: </span> Select category to change</p>
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>id</th>
                                            <th>Name</th>
                                            <th>Slug</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for category in categories %}
                                        <tr>
                                            <th scope="row">{{category.id}}</th>
                                            <td>{{category.name}}</td>
                                            <td>{{category.slug}}</td>
                                            <td>
                                                <div class="col-lg-4 col-md-6 col-sm-12">
                                                    <div class="form-group">

                                                        <!-- Button trigger modal -->
                                                        <button type="button"
                                                                class="btn btn-outline-primary block btn-lg"
                                                                data-toggle="modal" data-target="#default{{ category.id }}">
                                                            <div class="fonticon-wrap">
                                                                <i class="icon-delete"></i>
                                                            </div>
                                                        </button>
                                                        <br></br>
                                                        <button type="button"
                                                                class="btn btn-outline-primary block btn-lg"
                                                                data-toggle="#" data-target="#default">
                                                            <div class="fonticon-wrap">
                                                                <a href="{% url 'dashboard:edit_category' category.id %}"
                                                                   data-action="#">
                                                                    <i class="icon-edit"></i></a>
                                                            </div>
                                                        </button>

<!--                                                         Modal-->
                                                        <div class="modal fade text-xs-left" id="default{{ category.id }}" tabindex="-1"
                                                             role="dialog" aria-labelledby="myModalLabel1"
                                                             aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close"
                                                                                data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                        <h4 class="modal-title" id="myModalLabel1"></h4>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <h5>Are you sure?
                                                                        </h5>
                                                                        <p>Are you sure you want to delete the selected
                                                                            category? All of the following objects and
                                                                            their related items will be deleted:
                                                                            {{ category.name }}

                                                                        </p>

                                                                    </div>
                                                                    <form class="form" method="post" action="{% url 'dashboard:delete_category' category.id %}">{% csrf_token %}
                                                                        <div class="modal-footer">
                                                                            <button type="button"
                                                                                    class="btn grey btn-outline-secondary"
                                                                                    data-dismiss="modal">No take me back
                                                                            </button>
                                                                            <button type="submit"
                                                                                    class="btn btn-outline-primary">Yes,
                                                                                I'm
                                                                                sure changes
                                                                            </button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% endblock %}
                            {% endblock %}
                            </html>
                            </div>

dashboard/templates/dashboard/m_products.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% block table %}
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-xs-12 mb-1">
                <h2 class="content-header-title"></h2>
            </div>
            <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
                <div class="breadcrumb-wrapper col-xs-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Tables</a>
                        </li>
                        <li class="breadcrumb-item active">Basic Tables
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="content-body"><!-- Basic Tables start -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Products List</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
<!--                                    <li><a href="{% url 'dashboard:cat_add_modal' %}" data-action="#"><i-->
<!--                                            class="icon-plus4"></i></a></li>-->
                                    <li><a href="{% url 'dashboard:products_add' %}" data-action="#"><i
                                            class="icon-plus4"></i></a></li>
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                    <li><a data-action="close"><i class="icon-cross2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body collapse in">
                            <div class="card-block card-dashboard">
                                <p class="card-text"></p>
                                <p><span class="text-bold-600">Example 1:</span> Table with outer spacing</p>
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>id</th>
                                            <th>Name</th>
                                            <th>Slug</th>
                                            <th>Price</th>
                                            <th>Stock</th>
                                            <th>Created</th>
                                            <th>Updated</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for product in products %}
                                        <tr>
                                            <th scope="row">{{product.id}}</th>
                                            <td>{{product.name}}</td>
                                            <td>{{product.slug}}</td>
                                            <td>{{product.price}}</td>
                                            <td>{{product.stock}}</td>
                                            <td>{{product.created}}</td>
                                            <td>{{product.updated}}</td>
                                            <td>
                                                <div class="col-lg-4 col-md-6 col-sm-12">
                                                    <div class="form-group">

                                                        <!-- Button trigger modal -->
                                                        <button type="button"
                                                                class="btn btn-outline-primary block btn-lg"
                                                                data-toggle="modal" data-target="#default1{{ product.id }}">
                                                            <div class="fonticon-wrap">
                                                                <i class="icon-delete"></i>
                                                            </div>
                                                        </button>
                                                        <br></br>
                                                        <button type="button"
                                                                class="btn btn-outline-primary block btn-lg"
                                                                data-toggle="#" data-target="#default1">
                                                            <div class="fonticon-wrap">
                                                                <a href="{% url 'dashboard:cat_add_modal' %}"
                                                                   data-action="#">
                                                                    <i class="icon-edit"></i></a>
                                                            </div>
                                                        </button>


                                                        <!-- Modal -->
                                                        <div class="modal fade text-xs-left" id="default1{{ product.id }}" tabindex="-1"
                                                             role="dialog" aria-labelledby="myModalLabel1"
                                                             aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                                <div  class="modal-content">
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close"
                                                                                data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                        <h4 class="modal-title" id="myModalLabel1"></h4>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <h5>Are you sure?
                                                                        </h5>
                                                                        <p>Are you sure you want to delete the selected
                                                                            category? All of the following objects and
                                                                            their related items will be deleted:
                                                                            {{ product.name }}
                                                                        </p>

                                                                    </div>
                                                                    <form class="form" method="post" action="{% url 'dashboard:delete_product' product.id %}">{% csrf_token %}
                                                                    <div class="modal-footer">
                                                                        <button type="button"
                                                                                class="btn grey btn-outline-secondary"
                                                                                data-dismiss="modal">No take me back
                                                                        </button>
                                                                        <button type="submit"
                                                                                class="btn btn-outline-primary">Yes, I'm sure
                                                                        </button>

                                                                    </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% endblock %}
                            {% endblock %}
                            </html>