acereadymade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acereadymade_app.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('dashboard/', include('dashboard.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acereadymade_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from acereadymade_app import views


app_name = 'acereadymade_app'

urlpatterns = [
    # Account Parts
    path('', IndexView.as_view(), name='index'),
    path('signup/', CustomerSignUpView.as_view(), name='signup'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate,
            name='activate'),

    path('details/', DetailsView.as_view(), name='details'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('base/', BaseView.as_view(), name='base'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('myaccount/', MyAccoutView.as_view(), name='myaccount'),
    path('wishlist/', WishListView.as_view(), name='wishlist'),

    path('products/<int:category_id>/<slug:category_slug>/', ProductList.as_view(), name='product_list_by_category'),
    # category's product list

    path('products/', ProductList.as_view(), name='product_list'),
    path('products/detail/<slug:product_slug>/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    # product detail

]

cart/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import *
from . import views
from acereadymade_app import views


app_name = 'cart'

urlpatterns = [
    # Account Parts
    path('detail/', DetailView.as_view(), name='detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('ProceedCheckout/', ProceedCheckoutView.as_view(), name='proceedcheckout'),
    path('ViewCart/', ViewCartView.as_view(), name='viewcart'),
    path('OrderSummery/', OrderView.as_view(), name='order_list'),

    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', full_remove, name='full_remove'),
# addtocart_2
]

acereadymade_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django import forms
from datetime import date
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
import os

class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True)
    email_confirmed = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Customer_details(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    user_info = models.CharField(max_length=150, null=True)
    country = models.CharField(max_length=150)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    phone_no = models.IntegerField()

    def __str__(self):
        return self.user_info


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    # description = models.TextField(blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('acereadymade_app:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    featured = models.BooleanField(default=True)
    latest = models.BooleanField(default=True)
    topkurtha = models.BooleanField(default=True)
    topfeatured = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("acereadymade_app:product_detail", args=[self.id, self.slug])

acereadymade_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from .models import *
import datetime
from django.forms.utils import ErrorList
from django.contrib.auth.models import User



class CustomerSignupForm(UserCreationForm):
    # user_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    first_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Inform a valid email address.')
    phone_no = forms.IntegerField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone_no', 'password1', 'password2',)


class CustomerLogInForm(forms.Form):
    email = forms.EmailField(max_length=254, required=True,)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'Password',)

acereadymade_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View, FormView, ListView, DetailView
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomerSignupForm, CustomerLogInForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, HttpResponseRedirect
from django.utils.encoding import force_text
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from cart.models import *




# Create your views here.

class IndexView(ListView):
    template_name = 'acereadymade/index.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.filter(available=True).order_by('-created')[0:4]
        context['featured_products'] = Product.objects.filter(available=True, featured=True).order_by('-created')[0:5]
        context['latest_products'] = Product.objects.filter(available=True, latest=True).order_by('-created')[0:4]
        context['topkurtha_products'] = Product.objects.filter(available=True, topkurtha=True).order_by('-created')[0:4]
        context['topfeatured_products'] = Product.objects.filter(available=True, topfeatured=True).order_by('-created')[0:4]
        context['categories'] = Category.objects.all()
        context['gown'] = Category.objects.get(name='GOWN')
        context['kurtha_salwar'] = Category.objects.get(name='KURTHA SALWAR')
        context['saree'] = Category.objects.get(name='SAREE')
        context['one_piece'] = Category.objects.get(name='ONE PIECE')
        context['kurtha'] = Category.objects.get(name='KURTHA')
        print(99999999999999999999999999999,self.request.user)
        if self.request.user.is_authenticated:
            cart = Cart.objects.get(user=self.request.user)
            cart_item_count = CartItem.objects.filter(cart=cart).count
            context['total_item'] = cart_item_count
        return context


class CustomerSignUpView(View):
    form_class = CustomerSignupForm
    template_name = 'acereadymade/create-new.html'

    def get(self, request):
        form = self.form_class()
        categories = Category.objects.all()
        return render(request, self.template_name, {'form': form, 'categories': categories})

    def post(self, request):
        print("print method called")
        form = self.form_class(request.POST)

        print(form.is_valid(), request.POST)

        if form.is_valid():
            print("Inside form.isvalid111")
            user = form.save(commit=False)
            user.is_active = False
            user.username = user.first_name
            user.save()


            Customer.objects.create(user=user).save()
            Cart.objects.create(user=user)

            print(type(user), '111111111', 's', '222222222', type('s'))
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            print("after saving user.......................")
            message = render_to_string('acereadymade/account_activation_email.html',
                                       {
                                           'user': user,
                                           'domain': current_site.domain,
                                           'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                           'token': account_activation_token.make_token(user),
                                       })

            to_email = form.cleaned_data.get('email')

            email = EmailMessage(
                subject, message, to=[to_email]

            )
            email.send()

            return HttpResponse('Please Click the link to activate in your Gmail Inbox')

        return render(request, 'acereadymade/create-new.html')


class LogoutView(View):
    success_url = reverse_lazy('acereadymade_app:login')

    def get(self, request):
        logout(request)
        return redirect(self.success_url)


def account_activation_sent(request):
    return render(request, 'acereadymade/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        # user.email_confirmed = True
        # user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('acereadymade_app:index')
    else:
        return render(request, 'account_activation_invalid.html')


#
# class LogInView(ListView):
#     template_name = 'acereadymade/myaccount.html'
#     model = Category
#
#     def get_context_data(self, **kwargs):
#         context = super(LogInView, self).get_context_data(**kwargs)
#         context['categories'] = Category.objects.all()
#         return context


class LogInView(View):
    success_url = reverse_lazy('acereadymade_app:index')
    template_name = 'acereadymade/myaccount.html'
    form_class = CustomerLogInForm

    # template_name = 'myshop_app/login.html'
    def get(self, request):
        categories = Category.objects.all()
        form = self.form_class()
        return render(request, self.template_name, {'login_error': 'Please Login to Continue', 'categories': categories, 'form': form})

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        username = User.objects.get(email=str(email)).username
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(self.success_url)
        else:
            form = self.form_class()
            return render(request, 'acereadymade/myaccount.html', {'form': form})


class DetailsView(TemplateView):
    template_name = 'cart/viewfinish.html'


class ShopView(TemplateView):
    template_name = 'acereadymade/shop.html'

class BaseView(ListView):
    template_name = 'acereadymade/base.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        if self.request.user.is_authenticated:
            cart = Cart.objects.get(user=self.request.user)
            cart_item_count = CartItem.objects.filter(cart=cart).count
            context['total_item'] = cart_item_count
        return context


class ContactView(TemplateView):
    template_name = 'acereadymade/contact.html'

class MyAccoutView(TemplateView):
    template_name = 'acereadymade/myaccount.html'

class WishListView(TemplateView):
    template_name = 'acereadymade/wishlist.html'


class ProductList(ListView):
    template_name = 'acereadymade/shop.html'
    model = Product


    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        products = Product.objects.filter(available=True)
        context['topfeatured_products'] = Product.objects.filter(available=True, topfeatured=True)
        print(11111111111111111111, products)
        context['categories'] = Category.objects.all()
        try:
            category_slug = self.kwargs['category_slug']
        except KeyError:
            category_slug = None

        context['products'] = products
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            context['products'] = products.filter(category=category)
        return context


class ProductDetail(DetailView):
    template_name = 'cart/detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        context['product'] = Product.objects.get(slug=self.kwargs['product_slug'])
        context['categories'] = Category.objects.all()
        return context

acereadymade_app/templates/acereadymade/account_activation_email.html
Hi {{ user.username }},

Please click on the link below to confirm your registration:
http://{{ domain }}{% url 'acereadymade_app:activate' uidb64=uid token=token %}

acereadymade_app/templates/acereadymade/contact.html
{% extends 'acereadymade/base.html' %}
{% load static %}
{% block content %}

            <div class="contacthome">
            <div class="home_icon">
              <div class="container">
                <div class="row">
                  <div class="col-md-2">
                    <h1><a href="index.php"></a><g>CONTACT US</g></h1>
                  </div>
                </div>
              </div>
            </div>
          </div>



          <div class="contact_inpute">
            <div class="container">
              <div class="row">
                <div class="col-md-3">
                  <h1>Your Name (required)</h1>
                  <div class="input-group flex-nowrap">
  <div class="input-group-prepend">
  </div>
  <input type="text" class="form-control" aria-label="Username" aria-describedby="addon-wrapping">
</div>



 <h1>Your Email (required)</h1>
                  <div class="input-group flex-nowrap">
  <div class="input-group-prepend">
  </div>
  <input type="text" class="form-control" aria-label="Username" aria-describedby="addon-wrapping">
</div>




 <h1>Subject</h1>
                  <div class="input-group flex-nowrap">
  <div class="input-group-prepend">
  </div>
  <input type="text" class="form-control" aria-label="Username" aria-describedby="addon-wrapping">
</div>



  <h1>Your Message</h1>
   <div class="input-group flex-nowrap">
  <div class="input-group-prepend">
  </div>
  <textarea class="form-control" aria-label="With textarea"></textarea>
</div>



<h2><a href="#">Send</a></h2>
</div>


<div class="col-md-3">
</div>


  <div class="col-md-6">
    <div class="visitcontact">
    <h3>The <b>Visit Our Store</b></h3>
    <h4><g></g><b>Address:</b> Bhaisepati, Lalitpur, Nepal</h4>
    <h4><g></g><b>Phone:</b> Bhaisepati, Lalitpur, Nepal</h4>
    <h4><g></g><b>Email:</b> Bhaisepati, Lalitpur, Nepal</h4>
  </div>
</div>
</div>
</div>
</div>
{% endblock %}

acereadymade_app/templates/acereadymade/shop.html
{% extends 'acereadymade/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
{% block css %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100i,200,400&display=swap" rel="stylesheet">


    <link href="{% static 'vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/elegant-icon/style.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">


    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100i,200,400&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Product-Ace Radymade</title>
</head>
{% endblock %}
<body>


{% block content %}

<div class="storeshop">
    <div class="container">
        <div class="row">
            <div class="col-md-1">
                <h1>Sort By:</h1>
            </div>


            <div class="col-md-2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Sort by latest
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="faqs.php">Default Sorting</a>
                        <a class="dropdown-item" href="faqs.php">Sort by Popularty</a>
                        <a class="dropdown-item" href="faqs.php">Sort by Latest</a>
                        <a class="dropdown-item" href="faqs.php">Sort by average rating</a>
                        <a class="dropdown-item" href="faqs.php">Sort by price: low to high</a>
                        <a class="dropdown-item" href="faqs.php">Sort by price: high to low</a>
                    </div>
                </div>
            </div>


            <div class="col-md-7">
            </div>


            <div class="col-md-1">
                <h1>Show:</h1>
            </div>


            <div class="col-md-1">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">12
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="faqs.php">12</a>
                        <a class="dropdown-item" href="faqs.php">24</a>
                        <a class="dropdown-item" href="faqs.php">36</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br></br>
<!--&lt;!&ndash; our_latest_product_start &ndash;&gt;-->

<!--<section class="our_latest_product">-->
<!--    <div class="container">-->
<!--        <div class="s_m_title">-->
<!--        </div>-->

<!--        <div class="l_product_slider owl-carousel">-->
<!--        {% for product in products %}-->

<!--            <div class="item">-->

<!--                <div class="l_product_item">-->

<!--                    <div class="l_p_img">-->
<!--                        <a href="shop_cart.php"><img src="{{product.image.url}} " alt=""></a>-->

<!--                    </div>-->
<!--                    <div class="l_p_text">-->
<!--                        <ul>-->
<!--                            <li class="p_icon"><a href="#"><i class="icon_piechart"></i></a></li>-->
<!--                            <li><a class="add_cart_btn" href="alladdtocart_1.php">Add To Cart</a></li>-->
<!--                            <li class="p_icon"><a href="#"><i class="icon_heart_alt"></i></a></li>-->
<!--                        </ul>-->
<!--                        <h4>{{ product.name }}<br>FANCY SAREE WITH BLOUSE</h4>-->
<!--                        <h5>-->
<!--                            <del>₨ 3,500.00</del>-->
<!--                            ₨ {{ product.price }}-->
<!--                        </h5>-->

<!--                    </div>-->

<!--                </div>-->
<!--            </div>-->
<!--            {% endfor %}-->

<!--        </div>-->


<!--&lt;!&ndash;        <div class="l_product_slider owl-carousel">&ndash;&gt;-->
<!--&lt;!&ndash;        {% for product in topfeatured_products %}&ndash;&gt;-->

<!--&lt;!&ndash;            <div class="item">&ndash;&gt;-->

<!--&lt;!&ndash;                <div class="l_product_item">&ndash;&gt;-->

<!--&lt;!&ndash;                    <div class="l_p_img">&ndash;&gt;-->
<!--&lt;!&ndash;                        <a href="shop_cart.php"><img src="{{product.image.url}} " alt=""></a>&ndash;&gt;-->

<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--&lt;!&ndash;                    <div class="l_p_text">&ndash;&gt;-->
<!--&lt;!&ndash;                        <ul>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li class="p_icon"><a href="#"><i class="icon_piechart"></i></a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li><a class="add_cart_btn" href="alladdtocart_1.php">Add To Cart</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                            <li class="p_icon"><a href="#"><i class="icon_heart_alt"></i></a></li>&ndash;&gt;-->
<!--&lt;!&ndash;                        </ul>&ndash;&gt;-->
<!--&lt;!&ndash;                        <h4>{{ product.name }}<br>FANCY SAREE WITH BLOUSE</h4>&ndash;&gt;-->
<!--&lt;!&ndash;                        <h5>&ndash;&gt;-->
<!--&lt;!&ndash;                            <del>₨ 3,500.00</del>&ndash;&gt;-->
<!--&lt;!&ndash;                            ₨ {{ product.price }}&ndash;&gt;-->
<!--&lt;!&ndash;                        </h5>&ndash;&gt;-->

<!--&lt;!&ndash;                    </div>&ndash;&gt;-->

<!--&lt;!&ndash;                </div>&ndash;&gt;-->
<!--&lt;!&ndash;            </div>&ndash;&gt;-->
<!--&lt;!&ndash;            {% endfor %}&ndash;&gt;-->

<!--&lt;!&ndash;        </div>&ndash;&gt;-->

<!--    </div>-->
<!--</section>-->
<!--</div>-->

<!--<section class="featured-section">-->
<div class="dabulimg01">
    <div class="container">
        <div class="row">

            {% for product in products %}

            <div class="col-md-3 images-block">
       				<a href="{% url 'acereadymade_app:product_detail' product.slug product.id %}"> <img class="ARimg-A1 img-fluid" src="{{product.image.url}} "></a>
<!--       				<a href="{% url 'acereadymade_app:product_detail' product.slug product.id %}"> <img class="ARimg-A2 img-fluid" src="{{product.image.url}} "></a>-->
       				<h1>    </h1>
       				<h2>{{ product.name }}</h2>
       				<h3><s>₨ {{ product.price }}</s> ₨5,000.00</h3>


       				<h4><a href="#"><g></g></a><a href="{% url 'cart:add_cart' product.id %}"><p>ADD TO CART</p></a><a href="#"><g></g></a></h4>
				</div>

<!--            <div class="col-md-6 col-lg-3 ftco-animate">-->
<!--            <div class="product">-->
<!--              <a href="{% url 'acereadymade_app:product_detail' product.slug product.id %}" class="img-prod"><img class="img-fluid" src="{{product.image.url}} " alt="Colorlib Template">-->
<!--                <span class="status">-30</span>-->
<!--                <div class="overlay"></div>-->
<!--              </a>-->
<!--              <div class="text py-3 pb-4 px-3 text-center">-->
<!--                <h3><a href="alladdtocart_2.php">{{ product.name }}</a></h3>-->
<!--                <div class="d-flex">-->
<!--                  <div class="pricing">-->
<!--                    <p class="price"><span class="mr-2 price-dc">₨ {{ product.price }}</span><span class="price-sale">₨ 2,400.00</span></p>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="bottom-area d-flex px-3">-->
<!--                  <div class="m-auto d-flex">-->
<!--                    <a href="viewfinis.php" class="add-to-cart d-flex justify-content-center align-items-center text-center">-->
<!--                     <div class="iconeye">-->
<!--                      <h1></h1>-->
<!--                    </div>-->
<!--                    </a>-->
<!--                    <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">-->
<!--                      <div class="iconeye">-->
<!--                      <h1></h1>-->
<!--                    </div>-->
<!--                    </a>-->
<!--                    <a href="https://play.google.com/store/apps/details?id=com.xstudioo.acereadymade" class="heart d-flex justify-content-center align-items-center ">-->
<!--                      <div class="iconeye">-->
<!--                      <h1></h1>-->
<!--                    </div>-->
<!--                    </a>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
            {% endfor %}


        </div>
    </div>
</div>
<!--</section>-->


<div class="storeshop">
    <div class="container">
        <div class="row">
            <div class="col-md-1">
                <h1>Show:</h1>
            </div>


            <div class="col-md-1">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">12
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="faqs.php">12</a>
                        <a class="dropdown-item" href="faqs.php">24</a>
                        <a class="dropdown-item" href="faqs.php">36</a>
                    </div>
                </div>
            </div>


            <div class="col-md-8">
            </div>


            <div class="col-md-2">
                <br>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

{% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
{% endblock %}
</body>
</html>        

acereadymade_app/templates/acereadymade/wishlist.html
{% extends 'acereadymade/base.html' %}

{% block content %}
<div class="Product_name">
  <div class="container">
    <div class="Product_name1">
      <div class="row">
        <div class="col-md-2">
        </div>

        <div class="col-md-3">
          <h1>Product Name</h1>
        </div>
        <div class="col-md-3">
          <h1>Unit Price</h1>
        </div>
        <div class="col-md-3">
          <h1>Stock Status</h1>
        </div>

        <div class="col-md-1">
        </div>

        <div class="col-md-1">
        </div>
        <div class="col-md-10">
          <h2>No products were added to the wishlist</h2>
        </div>

        <div class="col-md-1">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}